In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
energy_data = pd.read_csv('energydata_complete (1).csv')
energy_data


date  Appliances  lights  ...  Tdewpoint        rv1        rv2
0      2016-01-11 17:00:00          60      30  ...   5.300000  13.275433  13.275433
1      2016-01-11 17:10:00          60      30  ...   5.200000  18.606195  18.606195
2      2016-01-11 17:20:00          50      30  ...   5.100000  28.642668  28.642668
3      2016-01-11 17:30:00          50      40  ...   5.000000  45.410389  45.410389
4      2016-01-11 17:40:00          60      40  ...   4.900000  10.084097  10.084097
...                    ...         ...     ...  ...        ...        ...        ...
19730  2016-05-27 17:20:00         100       0  ...  13.333333  43.096812  43.096812
19731  2016-05-27 17:30:00          90       0  ...  13.300000  49.282940  49.282940
19732  2016-05-27 17:40:00         270      10  ...  13.266667  29.199117  29.199117
19733  2016-05-27 17:50:00         420      10  ...  13.233333   6.322784   6.322784
19734  2016-05-27 18:00:00         430      10  ...  13.200000  34.118851  34.118851

[19735 rows x 29 columns]

In [18]:
x = energy_data[['T2']]
y = energy_data[['T6']]

In [19]:
print(x)

              T2
0      19.200000
1      19.200000
2      19.200000
3      19.200000
4      19.200000
...          ...
19730  25.890000
19731  25.754000
19732  25.628571
19733  25.414000
19734  25.264286

[19735 rows x 1 columns]


In [20]:
print(y)

              T6
0       7.026667
1       6.833333
2       6.560000
3       6.433333
4       6.366667
...          ...
19730  24.796667
19731  24.196667
19732  23.626667
19733  22.433333
19734  21.026667

[19735 rows x 1 columns]


In [23]:
print(x)

              T2
0      19.200000
1      19.200000
2      19.200000
3      19.200000
4      19.200000
...          ...
19730  25.890000
19731  25.754000
19732  25.628571
19733  25.414000
19734  25.264286

[19735 rows x 1 columns]


In [32]:
x.shape

(19735, 1)

In [24]:
print(y)

              T6
0       7.026667
1       6.833333
2       6.560000
3       6.433333
4       6.366667
...          ...
19730  24.796667
19731  24.196667
19732  23.626667
19733  22.433333
19734  21.026667

[19735 rows x 1 columns]


In [34]:
y.shape

(19735, 1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [25]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [27]:
y_pred = reg.predict(x_test)

In [28]:
print(y_pred)

[[ 6.74582472]
 [ 6.02789686]
 [ 7.58217368]
 ...
 [-0.18921041]
 [ 7.58217368]
 [ 8.75898327]]


In [35]:
y_pred.shape

(3947, 1)

In [38]:
from sklearn.metrics import r2_score
value = r2_score(y_test, y_pred)
round(value, 2)

0.65

In [56]:
energy_data_2= pd.read_csv('energydata_complete (1).csv')
energy_data_2['date'] = pd.to_numeric(energy_data_2['date'], errors='coerce')

In [57]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_energy_data = pd.DataFrame(scaler.fit_transform(energy_data_2), columns=energy_data_2.columns)
features_energy_data = normalised_energy_data.drop(columns=['date', 'lights'])
energy_data_target = normalised_energy_data['Appliances']


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:461: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:462: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [58]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [59]:
from sklearn.linear_model import LinearRegression
reg2 = LinearRegression()
reg2.fit(x_train, y_train)

LinearRegression()

In [73]:
y_pred = reg2.predict(x_test)
y_pred

array([[ 6.74582472],
       [ 6.02789686],
       [ 7.58217368],
       ...,
       [-0.18921041],
       [ 7.58217368],
       [ 8.75898327]])

In [62]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
round(mae, 3) 

2.829

In [63]:
from sklearn.metrics import r2_score
value = r2_score(y_test, y_pred)
round(value, 2)

0.65

In [67]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
round(rmse, 3) 

3.62

In [69]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)


Ridge(alpha=0.4)

In [74]:
y_pred2 = ridge_reg.predict(x_test)
y_pred2

array([[ 6.74583079],
       [ 6.02790671],
       [ 7.58217534],
       ...,
       [-0.18916781],
       [ 7.58217534],
       [ 8.75897873]])

In [75]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred2))
round(rmse, 3) 

3.62

In [76]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)


Lasso(alpha=0.001)

In [77]:
y_pred3 = lasso_reg.predict(x_test)
y_pred3

array([ 6.7459326 ,  6.02807196,  7.58220324, ..., -0.18845318,
        7.58220324,  8.75890264])

In [78]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred3))
round(rmse, 3) 

3.62