**Name: Oluwatomiwa Adeleke**


**ID: 146d130b5f41f000**

Importing Libaries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Answer to Question-14

In [4]:
#Read the  dataset, which is the CSV file 
energy_data = pd.read_csv('energydata_complete (1).csv')
energy_data


date  Appliances  lights  ...  Tdewpoint        rv1        rv2
0      2016-01-11 17:00:00          60      30  ...   5.300000  13.275433  13.275433
1      2016-01-11 17:10:00          60      30  ...   5.200000  18.606195  18.606195
2      2016-01-11 17:20:00          50      30  ...   5.100000  28.642668  28.642668
3      2016-01-11 17:30:00          50      40  ...   5.000000  45.410389  45.410389
4      2016-01-11 17:40:00          60      40  ...   4.900000  10.084097  10.084097
...                    ...         ...     ...  ...        ...        ...        ...
19730  2016-05-27 17:20:00         100       0  ...  13.333333  43.096812  43.096812
19731  2016-05-27 17:30:00          90       0  ...  13.300000  49.282940  49.282940
19732  2016-05-27 17:40:00         270      10  ...  13.266667  29.199117  29.199117
19733  2016-05-27 17:50:00         420      10  ...  13.233333   6.322784   6.322784
19734  2016-05-27 18:00:00         430      10  ...  13.200000  34.118851  34.118851

[19735 rows x 29 columns]

In [5]:
# assigning x = T2 and y = T6 
x = energy_data[['T2']]
y = energy_data[['T6']]

In [6]:
print(x)

              T2
0      19.200000
1      19.200000
2      19.200000
3      19.200000
4      19.200000
...          ...
19730  25.890000
19731  25.754000
19732  25.628571
19733  25.414000
19734  25.264286

[19735 rows x 1 columns]


In [7]:
print(y)

              T6
0       7.026667
1       6.833333
2       6.560000
3       6.433333
4       6.366667
...          ...
19730  24.796667
19731  24.196667
19732  23.626667
19733  22.433333
19734  21.026667

[19735 rows x 1 columns]


In [8]:
print(x)

              T2
0      19.200000
1      19.200000
2      19.200000
3      19.200000
4      19.200000
...          ...
19730  25.890000
19731  25.754000
19732  25.628571
19733  25.414000
19734  25.264286

[19735 rows x 1 columns]


In [9]:
x.shape

(19735, 1)

In [10]:
print(y)

              T6
0       7.026667
1       6.833333
2       6.560000
3       6.433333
4       6.366667
...          ...
19730  24.796667
19731  24.196667
19732  23.626667
19733  22.433333
19734  21.026667

[19735 rows x 1 columns]


In [11]:
y.shape

(19735, 1)

Splitting The Dataset

In [12]:
# Splitting The Dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

Linear Model

In [13]:
# Fitting a Linear Model for the relationship between x and y
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [14]:
y_pred = reg.predict(x_test)

In [15]:
print(y_pred)

[[ 6.74582472]
 [ 6.02789686]
 [ 7.58217368]
 ...
 [-0.18921041]
 [ 7.58217368]
 [ 8.75898327]]


In [16]:
y_pred.shape

(3947, 1)

R^2 Value and approximating it to 2 decimal decimal places

In [17]:
from sklearn.metrics import r2_score
value = r2_score(y_test, y_pred)
round(value, 2)

0.65

Answer to Question 14 - 20

In [18]:
energy_data_2= pd.read_csv('energydata_complete (1).csv')
energy_data_2['date'] = pd.to_numeric(energy_data_2['date'], errors='coerce')

Normalizing the dataset using the MinMaxScaler after removing the following columns: [“date”, “lights”]

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_energy_data = pd.DataFrame(scaler.fit_transform(energy_data_2), columns=energy_data_2.columns)
features_energy_data = normalised_energy_data.drop(columns=['date', 'lights'])
energy_data_target = normalised_energy_data['Appliances']


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:461: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:462: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


Splitting the dataset

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

Running a multiple linear regression using the training set and evaluating the model on the test set.


In [21]:
from sklearn.linear_model import LinearRegression
reg2 = LinearRegression()
reg2.fit(x_train, y_train)

LinearRegression()

In [22]:
y_pred = reg2.predict(x_test)
y_pred

array([[6.75111898],
       [6.03302778],
       [7.58765822],
       ...,
       [2.2352877 ],
       [7.58765822],
       [6.67708896]])

Mean Absolute Error (in two decimal places)

In [23]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
round(mae, 2) 

2.81

Residual Sum of Squares (in two decimal places)

In [24]:
from sklearn.metrics import r2_score
value = r2_score(y_test, y_pred)
round(value, 2)

0.65

Root Mean Squared Error (in three decimal places)

In [25]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
round(rmse, 3) 

3.61

Training a ridge regression model with an alpha value of 0.4

In [26]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)


Ridge(alpha=0.4)

In [27]:
y_pred2 = ridge_reg.predict(x_test)
y_pred2

array([[6.75112583],
       [6.033039  ],
       [7.58765996],
       ...,
       [2.23532209],
       [7.58765996],
       [6.67709626]])

Changes in the RMSE

In [28]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred2))
round(rmse, 3) 

3.61

Training a lasso regression model with an alpha value of 0.001

In [29]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)


Lasso(alpha=0.001)

In [30]:
y_pred3 = lasso_reg.predict(x_test)
y_pred3

array([6.75122539, 6.03320231, 7.58768526, ..., 2.23582255, 7.58768526,
       6.67720239])

RMSE with the lasso regression

In [31]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred3))
round(rmse, 3) 

3.61